export const PLAYER_HEALTH = 4;
export const PLAYER_LIVES = 3;

export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;
export const PLAYER_BULLET_MAX_COUNT = 10;
export const PLAYER_BULLET_INTERVAL = 300;
export const PLAYER_BULLET_SPEED = 300;
export const PLAYER_BULLET_LIFESPAN = 3;

export const ENEMY_ABSTRACT_SCORE = 100;
export const ENEMY_ABSTRACT_HEALTH = 2;
export const ENEMY_ABSTRACT_MOVEMENT_MAX_X = 80;
export const ENEMY_ABSTRACT_MOVEMENT_VERTICAL_VELOCITY = 15;
export const ENEMY_ABSTRACT_MOVEMENT_HORIZONTAL_VELOCITY = 14;
export const ENEMY_ABSTRACT_GROUP_SPAWN_INTERVAL = 5000;
export const ENEMY_ABSTRACT_GROUP_SPAWN_AT = 1000;

export const ENEMY_FIGHTER_SCORE = 200;
export const ENEMY_FIGHTER_HEALTH = 2;
export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 14;
export const ENEMY_FIGHTER_BULLET_MAX_COUNT = 10;
// change this to make fighter shoot faster (difficulty setting)
export const ENEMY_FIGHTER_BULLET_INTERVAL = 2500;
export const ENEMY_FIGHTER_BULLET_SPEED = -300;
export const ENEMY_FIGHTER_BULLET_LIFESPAN = 3;
export const ENEMY_FIGHTER_GROUP_SPAWN_INTERVAL = 6000;
export const ENEMY_FIGHTER_GROUP_SPAWN_AT = 3000;


export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;
export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;