export const PLAYER_MOVEMENT_HORIZONTAL_VELOCITY = 20;

export const ENEMY_ABSTRACT_MOVEMENT_MAX_X = 80;
export const ENEMY_ABSTRACT_MOVEMENT_VERTICAL_VELOCITY = 10;
export const ENEMY_ABSTRACT_MOVEMENT_HORIZONTAL_VELOCITY = 9
;
export const ENEMY_FIGHTER_MOVEMENT_VERTICAL_VELOCITY = 12;

export const COMPONENT_MOVEMENT_VERTICAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_VERTICAL_MAX_VELOCITY = 200;
export const COMPONENT_MOVEMENT_HORIZONTAL_DRAG = 0.01;
export const COMPONENT_MOVEMENT_HORIZONTAL_MAX_VELOCITY = 200;